services:

  nodes:
    image: ${nodes_image}
    build:
      context: ${nodes_context}
    volumes:
      - nodes_root_testnet:/root/testnet
    hostname: ${nodes_hostname}
    ports:
      - 9999:9999
    networks:
      monero_testnet:

networks:
  monero_testnet:
    ipam:
      driver: default
      config:
        - subnet: ${network_prefix}.0/24

volumes:
  nodes_root_testnet: