# Generated by Django 4.0.3 on 2022-03-08 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_remove_organizer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='fundraiser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='campaign.fundraiser'),
            preserve_default=False,
        ),
    ]
