# Generated by Django 4.0.3 on 2022-03-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_update_fundraiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='type',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
