# Generated by Django 4.0.3 on 2022-03-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_contribution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=12, default=0.0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizer',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='update',
            name='update',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
