# Generated by Django 4.0.3 on 2022-03-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_comment_comment_contribution_amount_fundraiser_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='amount',
        ),
    ]
