# Generated by Django 4.0.3 on 2022-03-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_contribution_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='message',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
