# Generated by Django 4.0.3 on 2022-03-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_contribution_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
